<?php
use CMS\Core\Csrf;
$menu=is_array($menu??null)?$menu:[]; $items=is_array($items??null)?$items:[]; $targets=is_array($targets??null)?$targets:[]; $oldItem=is_array($oldItem??null)?$oldItem:[];
$byParent=[]; foreach ($items as $it) $byParent[(int)($it['parent_id']??0)][]=$it;
$renderTree=function(int $parent=0,int $depth=0) use (&$renderTree,&$byParent,$menuId): void {
  foreach ($byParent[$parent]??[] as $item) { ?>
    <article class="menu-item-card" style="--menu-depth:<?= min(4,$depth) ?>">
      <div class="menu-item-main"><div><strong><?= e($item['label']) ?></strong><small><?= e(str_replace('_',' ',(string)$item['target_type'])) ?><?= (int)$item['is_enabled']===1?'':' · Hidden' ?></small></div></div>
      <details><summary>Edit</summary><form method="post" action="<?= e(admin_url('/menus/'.(int)$menuId.'/items/'.(int)$item['id'].'/edit')) ?>" class="menu-item-edit-form"><?= Csrf::field() ?>
        <div class="two-fields"><label>Label<input name="label" maxlength="120" required value="<?= e($item['label']) ?>"></label><label>Order<input type="number" name="sort_order" min="0" max="100000" value="<?= (int)$item['sort_order'] ?>"></label></div>
        <input type="hidden" name="target_type" value="<?= e($item['target_type']) ?>"><input type="hidden" name="target_id" value="<?= (int)($item['target_id']??0) ?>"><input type="hidden" name="target_model_id" value="<?= (int)($item['target_model_id']??0) ?>"><input type="hidden" name="custom_url" value="<?= e($item['custom_url']??'') ?>">
        <label>Parent<select name="parent_id"><option value="">Top level</option><?php foreach ($items as $p): if ((int)$p['id']===(int)$item['id']) continue; ?><option value="<?= (int)$p['id'] ?>" <?= (int)($item['parent_id']??0)===(int)$p['id']?'selected':'' ?>><?= e($p['label']) ?></option><?php endforeach; ?></select></label>
        <div class="inline-checks"><label class="check-label"><input type="checkbox" name="is_enabled" value="1" <?= (int)$item['is_enabled']===1?'checked':'' ?>> Visible</label><label class="check-label"><input type="checkbox" name="open_new_tab" value="1" <?= (int)$item['open_new_tab']===1?'checked':'' ?>> Open in new tab</label></div>
        <button class="button secondary small" type="submit">Save item</button>
      </form><form method="post" action="<?= e(admin_url('/menus/'.(int)$menuId.'/items/'.(int)$item['id'].'/delete')) ?>"><?= Csrf::field() ?><button class="text-button danger-text" type="submit">Delete item<?= !empty($byParent[(int)$item['id']])?' and children':'' ?></button></form></details>
    </article>
  <?php $renderTree((int)$item['id'],$depth+1); }
};
?>
<header class="page-header"><div><p class="eyebrow">Configuration · Menus</p><h1><?= $menuId?'Edit menu':'Create menu' ?></h1><p class="muted">Keep everyday navigation simple while Talvoro maintains stable content references underneath.</p></div><?php if ($menuId): ?><a class="button secondary compact" href="<?= e(admin_url('/menus')) ?>">All menus</a><?php endif; ?></header>
<?php if ($errors): ?><div class="notice error"><strong>Could not save.</strong><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<?php if (!empty($created)||!empty($saved)): ?><div class="notice success">Menu saved.</div><?php endif; ?>
<?php if (!empty($itemCreated)||!empty($itemSaved)||!empty($itemDeleted)): ?><div class="notice success">Menu items updated.</div><?php endif; ?>
<section class="card"><form method="post" action="<?= e($menuId?admin_url('/menus/'.$menuId.'/edit'):admin_url('/menus/new')) ?>"><?= Csrf::field() ?>
  <div class="two-fields"><label>Menu name<input name="name" required maxlength="120" value="<?= e($menu['name']??'') ?>" placeholder="Main navigation"></label><label>Location<select name="location"><?php foreach (['primary'=>'Primary header','mobile'=>'Mobile','footer'=>'Footer','unassigned'=>'Unassigned'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= ($menu['location']??'unassigned')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label></div>
  <label>Internal key <span class="optional-label">Auto-generated</span><input name="menu_key" maxlength="100" value="<?= e($menu['menu_key']??'') ?>" placeholder="main_navigation"><small class="field-help">Used internally. Leave blank on a new menu to generate it from the name.</small></label>
  <label>Description <span class="optional-label">Optional</span><textarea name="description" rows="3" maxlength="500"><?= e($menu['description']??'') ?></textarea></label>
  <div class="form-actions"><button class="button" type="submit">Save menu</button></div>
</form></section>
<?php if ($menuId): ?>
<section class="card"><div class="section-heading"><div><p class="eyebrow">Items</p><h2>Menu structure</h2><p class="muted">Nested links are supported. Editing order and parent is also a keyboard-accessible alternative to drag-and-drop.</p></div><span class="soft-badge"><?= count($items) ?> items</span></div><?php if (!$items): ?><div class="empty-state"><p>Add the first link below.</p></div><?php else: ?><div class="menu-tree"><?php $renderTree(); ?></div><?php endif; ?></section>
<section class="card"><div class="section-heading"><div><p class="eyebrow">Add link</p><h2>New menu item</h2></div></div>
<form method="post" action="<?= e(admin_url('/menus/'.$menuId.'/items')) ?>" class="menu-item-create" data-menu-item-form><?= Csrf::field() ?>
  <div class="two-fields"><label>Label<input name="label" required maxlength="120" value="<?= e($oldItem['label']??'') ?>" placeholder="About us"></label><label>Link type<select name="target_type" data-menu-target-type><option value="page">Page</option><option value="post">Blog post</option><option value="content_entry">Structured content</option><option value="custom">Custom URL</option></select></label></div>
  <div data-menu-target="page"><label>Find page<input type="search" data-menu-target-search data-target-kind="page" data-search-url="<?= e(admin_url('/menus/target-search')) ?>" placeholder="Search pages…" autocomplete="off"></label><label>Page<select name="target_id" data-menu-target-select><option value="">Choose a page…</option><?php foreach ($targets['pages']??[] as $t): ?><option value="<?= (int)$t['id'] ?>"><?= e($t['label'].' — '.$t['secondary']) ?></option><?php endforeach; ?></select></label></div>
  <div data-menu-target="post" hidden><label>Find blog post<input type="search" data-menu-target-search data-target-kind="post" data-search-url="<?= e(admin_url('/menus/target-search')) ?>" placeholder="Search posts…" autocomplete="off"></label><label>Blog post<select data-target-name="target_id" data-menu-target-select><option value="">Choose a post…</option><?php foreach ($targets['posts']??[] as $t): ?><option value="<?= (int)$t['id'] ?>"><?= e($t['label']) ?></option><?php endforeach; ?></select></label></div>
  <div data-menu-target="content_entry" hidden><label>Find structured content<input type="search" data-menu-target-search data-target-kind="content_entry" data-search-url="<?= e(admin_url('/menus/target-search')) ?>" placeholder="Search entries or model…" autocomplete="off"></label><label>Structured content<select data-target-name="target_id" data-menu-target-select><option value="">Choose content…</option><?php foreach ($targets['content']??[] as $t): ?><option value="<?= (int)$t['id'] ?>" data-model-id="<?= (int)$t['model_id'] ?>"><?= e($t['label'].' — '.$t['secondary']) ?></option><?php endforeach; ?></select></label><input type="hidden" name="target_model_id" value="" data-target-model></div>
  <div data-menu-target="custom" hidden><label>URL<input data-target-name="custom_url" placeholder="/contact or https://example.com"></label></div>
  <div class="three-fields"><label>Parent<select name="parent_id"><option value="">Top level</option><?php foreach ($items as $p): ?><option value="<?= (int)$p['id'] ?>"><?= e($p['label']) ?></option><?php endforeach; ?></select></label><label>Order<input type="number" name="sort_order" min="0" max="100000" value="100"></label><div class="inline-checks"><label class="check-label"><input type="checkbox" name="is_enabled" value="1" checked> Visible</label><label class="check-label"><input type="checkbox" name="open_new_tab" value="1"> New tab</label></div></div>
  <div class="form-actions"><button class="button" type="submit">Add menu item</button></div>
</form></section>
<section class="card danger-zone"><h2>Delete menu</h2><p>Only the menu and its links are removed. Pages, posts and structured content are never deleted.</p><form method="post" action="<?= e(admin_url('/menus/'.$menuId.'/delete')) ?>"><?= Csrf::field() ?><label class="confirm-check"><input type="checkbox" name="confirm_delete" value="1" required> Confirm menu deletion</label><button class="button danger" type="submit">Delete menu</button></form></section>
<?php endif; ?>
