<?php use CMS\Core\Csrf; ?>
<header class="page-header editor-header"><div><a class="back-link" href="<?= e(admin_url('/content-models/'.(int)$model['id'].'/edit')) ?>">← <?= e($model['plural_name']) ?></a><p class="eyebrow">Content model field</p><h1><?= $fieldId?'Edit field':'Add field' ?></h1><p class="muted">Give editors a clear field with validation appropriate to the information you are collecting.</p></div></header>
<?php if ($errors): ?><div class="alert error"><strong>Please correct the following:</strong><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<form method="post" action="<?= e($fieldId ? admin_url('/content-models/'.(int)$model['id'].'/fields/'.$fieldId.'/edit') : admin_url('/content-models/'.(int)$model['id'].'/fields/new')) ?>" class="card editor-card stack schema-field-form" data-schema-field-form>
<?= Csrf::field() ?>
<div class="form-grid two"><label>Label<input name="label" value="<?= e($field['label']) ?>" maxlength="120" required placeholder="Date of birth" data-field-label></label><label>Field type<select name="field_type" data-field-type><?php foreach ($types as $key=>$label): ?><option value="<?= e($key) ?>" <?= $field['field_type']===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label></div>
<details class="advanced-panel"><summary>Advanced field identity</summary><div class="form-grid two advanced-panel-body"><label>Internal field key<input name="field_key" value="<?= e($field['field_key']) ?>" maxlength="100" <?= $fieldId?'readonly':'' ?> placeholder="date_of_birth" data-field-key><small class="field-help"><?= $fieldId?'Stable after creation so saved content and future APIs remain compatible.':'Generated automatically from the label. Change it only when you have a specific integration reason.' ?></small></label><label>Order<input type="number" min="0" max="10000" name="sort_order" value="<?= (int)$field['sort_order'] ?>"><small class="field-help">You can also reorder fields with drag and drop or the Up/Down buttons.</small></label></div></details>
<label>Placeholder<input name="placeholder" value="<?= e($field['placeholder']??'') ?>" maxlength="255" placeholder="Optional editor hint"></label>
<label>Help text<textarea name="help_text" rows="2" maxlength="500" placeholder="Explain what belongs in this field."><?= e($field['help_text']??'') ?></textarea></label>
<label class="confirm-check"><input type="checkbox" name="is_required" value="1" <?= (int)($field['is_required']??0)===1?'checked':'' ?>> Required before the entry can be saved.</label>

<div class="field-type-options" data-options-for="select multiselect"><label>Options<textarea name="options" rows="6" placeholder="Male&#10;Female&#10;Unknown"><?= e($field['options']??'') ?></textarea><small class="field-help">One option per line.</small></label></div>
<div class="field-type-options" data-options-for="relation"><div class="form-grid two"><label>Relates to<select name="target_model_id"><option value="0">Choose model...</option><?php foreach ($models as $target): ?><option value="<?= (int)$target['id'] ?>" <?= (int)($field['target_model_id']??0)===(int)$target['id']?'selected':'' ?>><?= e($target['plural_name']) ?><?= ($target['status']??'active')!=='active'?' - Disabled':'' ?></option><?php endforeach; ?></select></label><label>Relationship<select name="relation_type"><option value="many_to_one" <?= ($field['relation_type']??'many_to_one')==='many_to_one'?'selected':'' ?>>Many-to-one - one selection per entry</option><option value="one_to_one" <?= ($field['relation_type']??'')==='one_to_one'?'selected':'' ?>>One-to-one - target can only be assigned once</option><option value="one_to_many" <?= ($field['relation_type']??'')==='one_to_many'?'selected':'' ?>>One-to-many - multiple unique targets</option><option value="many_to_many" <?= ($field['relation_type']??'')==='many_to_many'?'selected':'' ?>>Many-to-many - multiple shared targets</option></select><small class="field-help">For Mother -> Dog, many-to-one is usually correct. Use one-to-one only when the target must not be assigned elsewhere.</small></label></div></div>
<div class="field-type-options" data-options-for="component repeater"><label>Reusable component<select name="component_id"><option value="0">Choose component…</option><?php foreach ($components as $component): ?><option value="<?= (int)$component['id'] ?>" <?= (int)($field['component_id']??0)===(int)$component['id']?'selected':'' ?>><?= e($component['name']) ?><?= ($component['status']??'active')!=='active'?' · Disabled':'' ?></option><?php endforeach; ?></select></label></div>
<div class="field-type-options" data-options-for="number"><div class="form-grid three"><label>Minimum<input type="number" step="any" name="min" value="<?= e((string)($field['min']??'')) ?>"></label><label>Maximum<input type="number" step="any" name="max" value="<?= e((string)($field['max']??'')) ?>"></label><label>Step<input type="number" step="any" name="step" value="<?= e((string)($field['step']??'')) ?>"></label></div></div>
<div class="field-type-options" data-options-for="text textarea"><label>Maximum characters<input type="number" min="0" max="100000" name="max_length" value="<?= e((string)($field['max_length']??'')) ?>" placeholder="Optional"></label></div>
<div class="field-type-options" data-options-for="text textarea number boolean date datetime select multiselect email url"><label>Default value<input name="default_value" value="<?= e((string)($field['default_value']??'')) ?>" maxlength="1000" placeholder="Optional"><small class="field-help">Applied when a new entry is created and the editor has not entered a value.</small></label></div>
<details class="advanced-panel"><summary>Validation & search</summary><div class="advanced-panel-body toggle-grid"><label class="toggle-card" data-options-for="text textarea number date datetime select multiselect email url"><input type="checkbox" name="unique" value="1" <?= (int)($field['unique']??0)===1?'checked':'' ?>><span><strong>Unique value</strong><small>Prevent two entries in this model from saving the same value. Talvoro checks existing data before this can be enabled.</small></span></label><label class="toggle-card" data-options-for="text textarea rich_text number date datetime select multiselect email url"><input type="checkbox" name="searchable" value="1" <?= (int)($field['searchable']??0)===1?'checked':'' ?>><span><strong>Include in content search</strong><small>Index this field so model listings and future global content search can find its value.</small></span></label></div></details>

<div class="form-actions"><button class="button" type="submit"><?= $fieldId?'Save field':'Add field' ?></button></div>
</form>
<?php if ($fieldId): ?><section class="danger-zone"><div><strong><?= (int)$dataCount>0?'Archive field':'Delete unused field' ?></strong><p><?php if ((int)$dataCount>0): ?><strong><?= (int)$dataCount ?></strong> <?= (int)$dataCount===1?'record currently contains':'records currently contain' ?> data in this field. Talvoro will preserve that data and hide the field from editors instead of deleting it.<?php else: ?>No saved entry currently contains data in this field, so it can be removed safely.<?php endif; ?></p></div><form method="post" action="<?= e(admin_url('/content-models/'.(int)$model['id'].'/fields/'.$fieldId.'/delete')) ?>"><?= Csrf::field() ?><?php if ((int)$dataCount>0): ?><label class="confirm-check"><input type="checkbox" name="confirm_archive" value="1" required> I understand this archives the field while preserving existing values.</label><button class="button danger" type="submit">Archive field</button><?php else: ?><label class="confirm-check"><input type="checkbox" name="confirm_delete" value="1" required> I understand this permanently removes this unused field definition.</label><button class="button danger" type="submit">Delete field</button><?php endif; ?></form></section><?php endif; ?>
<script src="/assets/js/schema-fields.js?v=<?= e(app_version()) ?>" defer></script>
