<?php
use CMS\Core\ContentModels;
use CMS\Core\Csrf;
use CMS\Core\HomePage;
$values=is_array($entry['values']??null)?$entry['values']:[];
$autosave=is_array($autosave??null)?$autosave:null;
$autosaveJson=json_encode($autosave['payload']??[],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?:'{}';
$mediaMap=[]; foreach ($mediaAssets as $asset) $mediaMap[(int)$asset['id']]=$asset;
$richToolbar=static function(): string { return '<div class="rich-toolbar" data-rich-toolbar role="toolbar" aria-label="Formatting"><button type="button" data-command="bold"><strong>B</strong></button><button type="button" data-command="italic"><em>I</em></button><button type="button" data-block="H2">H2</button><button type="button" data-block="H3">H3</button><button type="button" data-command="insertUnorderedList">• List</button><button type="button" data-action="link">Link</button><button type="button" data-action="clear">Clear</button></div>'; };
$renderScalar=null;
$renderScalar=static function(array $field,mixed $value,string $name,string $idPrefix='') use (&$renderScalar,$mediaAssets,$mediaMap,$relationOptions,$relationAccess,$relationSearchUrl,$entry,$richToolbar,$canBrowseMedia): void {
    $key=(string)$field['field_key']; $type=(string)$field['field_type']; $settings=is_array($field['settings']??null)?$field['settings']:ContentModels::decodeSettings($field['settings_json']??null); $id=$idPrefix!==''?$idPrefix:'field-'.$key; $required=(int)$field['is_required']===1;
    echo '<div class="structured-field structured-field-'.e($type).'">';
    if ($type==='boolean') { echo '<label class="toggle-card"><input type="checkbox" name="'.e($name).'" value="1"'.(!empty($value)?' checked':'').'><span><strong>'.e($field['label']).'</strong>'; if (!empty($field['help_text'])) echo '<small>'.e($field['help_text']).'</small>'; echo '</span></label></div>'; return; }
    echo '<label for="'.e($id).'">'.e($field['label']).($required?' <span class="required-mark">Required</span>':'').'</label>';
    $placeholder=e((string)($field['placeholder']??''));
    switch ($type) {
        case 'textarea': echo '<textarea id="'.e($id).'" name="'.e($name).'" rows="5" placeholder="'.$placeholder.'">'.e((string)$value).'</textarea>'; break;
        case 'rich_text': $html=(string)$value; echo '<div class="rich-editor structured-rich-editor" data-rich-editor>'.$richToolbar().'<div class="rich-editable" contenteditable="true" data-rich-editable data-placeholder="Write content…">'.$html.'</div><textarea class="rich-source" data-rich-source hidden>'.e($html).'</textarea><textarea name="'.e($name).'" data-rich-hidden hidden>'.e($html).'</textarea></div>'; break;
        case 'number': echo '<input id="'.e($id).'" type="number" step="'.e((string)($settings['step']??'any')).'"'.(isset($settings['min'])?' min="'.e((string)$settings['min']).'"':'').(isset($settings['max'])?' max="'.e((string)$settings['max']).'"':'').' name="'.e($name).'" value="'.e((string)$value).'" placeholder="'.$placeholder.'">'; break;
        case 'date': echo '<input id="'.e($id).'" type="date" name="'.e($name).'" value="'.e((string)$value).'">'; break;
        case 'datetime': echo '<input id="'.e($id).'" type="datetime-local" name="'.e($name).'" value="'.e(str_replace(' ','T',(string)$value)).'">'; break;
        case 'select': echo '<select id="'.e($id).'" name="'.e($name).'"><option value="">— Choose —</option>'; foreach ((array)($settings['options']??[]) as $opt) echo '<option value="'.e($opt).'"'.((string)$value===(string)$opt?' selected':'').'>'.e($opt).'</option>'; echo '</select>'; break;
        case 'multiselect': $selected=array_map('strval',(array)$value); echo '<select id="'.e($id).'" name="'.e($name).'[]" multiple size="'.min(8,max(3,count((array)($settings['options']??[])))).'">'; foreach ((array)($settings['options']??[]) as $opt) echo '<option value="'.e($opt).'"'.(in_array((string)$opt,$selected,true)?' selected':'').'>'.e($opt).'</option>'; echo '</select>'; break;
        case 'media':
            $selected=(int)$value;
            if (!$canBrowseMedia) { if ($selected>0) echo '<input type="hidden" name="'.e($name).'" value="'.$selected.'">'; echo '<div id="'.e($id).'" class="notice neutral compact">'.($selected>0?'Existing media is preserved. ':'').'Media Library access is required to change this field.</div>'; break; }
            echo '<select id="'.e($id).'" name="'.e($name).'"><option value="0">— No image —</option>'; foreach ($mediaAssets as $asset) echo '<option value="'.(int)$asset['id'].'"'.($selected===(int)$asset['id']?' selected':'').'>'.e($asset['label']).' · '.(int)$asset['width'].'×'.(int)$asset['height'].'</option>'; echo '</select>'; if ($selected>0&&isset($mediaMap[$selected])) echo '<figure class="structured-media-preview"><img src="'.e($mediaMap[$selected]['path']).'" alt=""></figure>'; break;
        case 'gallery':
            $selected=array_values(array_unique(array_filter(array_map('intval',(array)$value),static fn(int $id): bool => $id>0)));
            if (!$canBrowseMedia) { foreach ($selected as $selectedId) echo '<input type="hidden" name="'.e($name).'[]" value="'.$selectedId.'">'; echo '<div id="'.e($id).'" class="notice neutral compact">'.($selected?'Existing gallery selections are preserved. ':'').'Media Library access is required to change this field.</div>'; break; }
            echo '<select id="'.e($id).'" name="'.e($name).'[]" multiple size="8">'; foreach ($mediaAssets as $asset) echo '<option value="'.(int)$asset['id'].'"'.(in_array((int)$asset['id'],$selected,true)?' selected':'').'>'.e($asset['label']).'</option>'; echo '</select><small class="field-help">Hold Command/Ctrl to select multiple images.</small>'; break;
        case 'relation':
            $options=$relationOptions[$key]??[]; $multiple=ContentModels::relationAllowsMultiple($settings); $canSearch=(bool)($relationAccess[$key]??false);
            $resultsId=$id.'-results';
            echo '<div class="relation-picker" data-relation-picker data-search-url="'.e($relationSearchUrl).'" data-field-key="'.e($key).'" data-multiple="'.($multiple?'1':'0').'" data-current-entry-id="'.(int)($entry['id']??0).'" data-input-name="'.e($name).'">';
            echo '<div class="relation-selected" data-relation-selected>';
            foreach ($options as $opt) {
                echo '<span class="relation-chip" data-relation-selected-id="'.(int)$opt['id'].'"><span>'.e($opt['title']).' <small>'.e(ucfirst((string)$opt['status'])).'</small></span><input type="hidden" name="'.e($name).'[]" value="'.(int)$opt['id'].'">';
                if ($canSearch) echo '<button type="button" data-relation-remove aria-label="Remove '.e($opt['title']).'">Remove</button>';
                echo '</span>';
            }
            echo '</div>';
            if ($canSearch) echo '<input id="'.e($id).'" type="search" autocomplete="off" placeholder="Search related entries..." role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="'.e($resultsId).'" data-relation-query>';
            else echo '<div id="'.e($id).'" class="notice neutral compact">Related entries are preserved, but your role does not have access to browse the target content model.</div>';
            echo '<div id="'.e($resultsId).'" class="relation-results" role="listbox" data-relation-results hidden></div></div>';
            break;
        case 'url': echo '<input id="'.e($id).'" type="text" inputmode="url" name="'.e($name).'" value="'.e((string)$value).'" placeholder="'.$placeholder.'">'; break;
        case 'email': echo '<input id="'.e($id).'" type="email" name="'.e($name).'" value="'.e((string)$value).'" placeholder="'.$placeholder.'">'; break;
        default: echo '<input id="'.e($id).'" type="text" name="'.e($name).'" value="'.e((string)$value).'" placeholder="'.$placeholder.'">';
    }
    if (!empty($field['help_text'])) echo '<small class="field-help">'.e($field['help_text']).'</small>';
    echo '</div>';
};
$renderComponent=static function(array $field,mixed $value,string $baseName,bool $repeater=false) use (&$renderScalar): void {
    $settings=is_array($field['settings']??null)?$field['settings']:ContentModels::decodeSettings($field['settings_json']??null); $componentId=(int)($settings['component_id']??0); $component=ContentModels::component($componentId); $subfields=ContentModels::componentFields($componentId);
    if (!$component) { echo '<div class="notice warning">Component definition is missing.</div>'; return; }
    $items=$repeater?(is_array($value)?array_values($value):[]):[is_array($value)?$value:[]]; if ($repeater&&$items===[]) $items=[[]];
    echo '<section class="structured-component'.($repeater?' structured-repeater':'').'"'.($repeater?' data-repeater data-repeater-name="'.e($baseName).'"':'').'><div class="structured-component-head"><div><strong>'.e($field['label']).'</strong><small>'.e($component['name']).($repeater?' · repeating':'').'</small></div>'.($repeater?'<button type="button" class="button secondary small" data-repeater-add>Add item</button>':'').'</div><div data-repeater-items>';
    foreach ($items as $index=>$item) { echo '<article class="component-item" data-repeater-item><div class="component-item-head"><strong>'.e($component['name']).($repeater?' '.($index+1):'').'</strong>'.($repeater?'<button type="button" class="text-link danger-link" data-repeater-remove>Remove</button>':'').'</div>'; foreach ($subfields as $sub) { $subName=$repeater?$baseName.'['.$index.']['.$sub['field_key'].']':$baseName.'['.$sub['field_key'].']'; $subId='comp-'.$field['field_key'].($repeater?'-'.$index:'').'-'.$sub['field_key']; $renderScalar($sub,$item[$sub['field_key']]??null,$subName,$subId); } echo '</article>'; }
    echo '</div>';
    if ($repeater) { echo '<template data-repeater-template><article class="component-item" data-repeater-item><div class="component-item-head"><strong>'.e($component['name']).' __NUMBER__</strong><button type="button" class="text-link danger-link" data-repeater-remove>Remove</button></div>'; foreach ($subfields as $sub) $renderScalar($sub,null,$baseName.'[__INDEX__]['.$sub['field_key'].']','comp-'.$field['field_key'].'-__INDEX__-'.$sub['field_key']); echo '</article></template>'; }
    echo '</section>';
};
?>
<header class="page-header editor-header"><div><a class="back-link" href="<?= e(admin_url('/content/'.$model['slug'])) ?>">&larr; <?= e($model['plural_name']) ?></a><p class="eyebrow">Structured content</p><h1><?= $isEdit?'Edit '.e($model['singular_name']):'New '.e($model['singular_name']) ?></h1><p class="muted">The form below is generated from the <?= e($model['singular_name']) ?> content model.</p></div><?php if ($isEdit): ?><div class="header-actions"><?php if ((int)$model['has_urls']===1&&$entry['status']==='published'): ?><a class="button secondary" href="/<?= e($model['slug']) ?>/<?= e($entry['slug']) ?>" target="_blank" rel="noopener">View live</a><?php endif; ?><a class="button secondary" href="<?= e(admin_url('/content/'.$model['slug'].'/'.(int)$entry['id'].'/preview')) ?>" target="_blank" rel="noopener">Preview</a></div><?php endif; ?></header>
<?php if (!empty($created)): ?><div class="notice success"><?= e($model['singular_name']) ?> created.</div><?php endif; ?><?php if (!empty($saved)): ?><div class="notice success">Changes saved.</div><?php endif; ?>
<?php if ($autosave): ?><div class="notice autosave-recovery" data-autosave-recovery><strong>Newer autosave available.</strong> Talvoro saved unsaved changes at <?= e(CMS\Core\Posts::displayDate($autosave['saved_at'],'j M Y · H:i')) ?>. <button type="button" class="text-link" data-restore-autosave>Restore autosave</button><script type="application/json" data-autosave-payload><?= $autosaveJson ?></script></div><?php endif; ?>
<?php if ($errors): ?><div class="alert error"><strong>Please correct the following:</strong><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>

<form method="post" action="<?= e($isEdit?admin_url('/content/'.$model['slug'].'/'.(int)$entry['id'].'/edit'):admin_url('/content/'.$model['slug'].'/new')) ?>" class="structured-entry-form" data-content-safety-form data-internal-link-url="<?= e(admin_url('/internal-links')) ?>"<?= $isEdit && $autosaveUrl!==''?' data-autosave-url="'.e($autosaveUrl).'"':'' ?>>
<?= Csrf::field() ?><input type="hidden" name="model_id" value="<?= (int)$model['id'] ?>">
<div class="structured-entry-layout">
<section class="stack">
    <section class="card editor-card stack"><label>Title<input class="post-title-input" name="title" value="<?= e($entry['title']??'') ?>" maxlength="255" required autofocus data-structured-title placeholder="<?= e($model['singular_name']) ?> title"></label><?php if ((int)$model['has_urls']===1): ?><details class="advanced-panel"><summary>URL settings</summary><div class="advanced-panel-body"><label>URL slug<div class="slug-field"><span>/<?= e($model['slug']) ?>/</span><input name="slug" value="<?= e($entry['slug']??'') ?>" maxlength="191" data-structured-slug placeholder="created-from-title"></div><small class="field-help">Talvoro generates this from the title for new entries. Existing URLs stay stable unless you deliberately edit the slug.</small></label><?php if ($isEdit && (int)$model['is_public']===1 && ($entry['status']??'draft')==='published'): ?><label class="confirm-check compact-check"><input type="checkbox" name="keep_old_url" value="1" checked> Keep the old address working with a permanent 301 redirect if I change this URL.</label><?php endif; ?></div></details><?php endif; ?></section>
    <section class="card editor-card stack"><div class="section-heading"><div><p class="eyebrow">Content</p><h2><?= e($model['singular_name']) ?> fields</h2></div><span class="health-chip"><?= count($fields) ?> fields</span></div>
    <?php if ((int)$model['enable_featured_image']===1): $featuredId=(int)($entry['featured_media_id']??0); ?>
    <div class="structured-field"><label for="featured-media">Featured image</label><?php if (!$canBrowseMedia): ?><?php if ($featuredId>0): ?><input type="hidden" name="featured_media_id" value="<?= $featuredId ?>"><?php endif; ?><div id="featured-media" class="notice neutral compact"><?= $featuredId>0?'The existing featured image is preserved. ':'' ?>Media Library access is required to change it.</div><?php else: ?><select id="featured-media" name="featured_media_id"><option value="0">No featured image</option><?php foreach ($mediaAssets as $asset): ?><option value="<?= (int)$asset['id'] ?>" <?= $featuredId===(int)$asset['id']?'selected':'' ?>><?= e($asset['label']) ?> - <?= (int)$asset['width'] ?>x<?= (int)$asset['height'] ?></option><?php endforeach; ?></select><small class="field-help">Uses the existing Talvoro Media Library. Upload and manage files from Content &rarr; Media.</small><?php if ($featuredId>0&&isset($mediaMap[$featuredId])): ?><figure class="structured-media-preview"><img src="<?= e($mediaMap[$featuredId]['path']) ?>" alt=""></figure><?php endif; ?><?php endif; ?></div>
    <?php endif; ?>
    <?php if (!$fields): ?><div class="notice neutral">This model has no custom fields yet. <a href="<?= e(admin_url('/content-models/'.(int)$model['id'].'/edit')) ?>">Configure fields</a>.</div><?php endif; ?>
    <?php foreach ($fields as $field): $key=(string)$field['field_key']; $value=$values[$key]??null; if ($field['field_type']==='component') $renderComponent($field,$value,'fields['.$key.']',false); elseif ($field['field_type']==='repeater') $renderComponent($field,$value,'fields['.$key.']',true); else $renderScalar($field,$value,'fields['.$key.']'); endforeach; ?>
    </section>
</section>
<aside class="stack structured-entry-sidebar">
    <section class="card publish-card"><div class="section-heading"><div><p class="eyebrow">Publishing</p><h2>Visibility</h2></div></div><label>Status<select name="status" data-structured-status><option value="draft" <?= ($entry['status']??'draft')==='draft'?'selected':'' ?>>Draft - private</option><?php if ($canPublish): ?><option value="published" <?= ($entry['status']??'')==='published'?'selected':'' ?>>Published</option><?php if ((int)$model['enable_scheduling']===1): ?><option value="scheduled" <?= ($entry['status']??'')==='scheduled'?'selected':'' ?>>Scheduled</option><?php endif; ?><?php endif; ?></select></label><?php if ($canPublish && (int)$model['enable_scheduling']===1): ?><label>Publish date &amp; time<input type="datetime-local" name="published_at_local" value="<?= e((string)($entry['published_at_local']??'')) ?>" data-structured-publish-time><small class="field-help">Required for Scheduled. Times use the site timezone.</small></label><?php endif; ?><button class="button full" type="submit"><?= $isEdit?'Save changes':'Create '.$model['singular_name'] ?></button><?php if ($isEdit && (int)$model['enable_autosave']===1): ?><div class="autosave-status" data-autosave-status>Autosave ready</div><?php endif; ?><?php if ($isEdit && (int)$model['enable_revisions']===1): ?><a class="button secondary full" href="<?= e(admin_url('/content/'.$model['slug'].'/'.(int)$entry['id'].'/revisions')) ?>">Revision history - <?= (int)$revisionCount ?></a><?php endif; ?></section>
    <?php if ((int)$model['enable_seo']===1): $socialMediaId=(int)($entry['social_media_id']??0); ?><section class="card stack"><div class="section-heading"><div><p class="eyebrow">SEO</p><h2>Search &amp; social</h2></div></div><label>SEO title<input name="seo_title" value="<?= e($entry['seo_title']??'') ?>" maxlength="255" placeholder="Defaults to the entry title"></label><label>Meta description<textarea name="seo_description" rows="4" maxlength="500" placeholder="Talvoro can fall back to the first useful text field."><?= e($entry['seo_description']??'') ?></textarea></label><details class="advanced-panel"><summary>Advanced SEO</summary><div class="advanced-panel-body stack"><label>Canonical URL<input type="url" name="canonical_url" value="<?= e($entry['canonical_url']??'') ?>" maxlength="500" placeholder="Optional full https:// URL"></label><label>Robots<select name="robots"><?php foreach (['index,follow'=>'Index and follow','index,nofollow'=>'Index, do not follow links','noindex,follow'=>'Do not index, follow links','noindex,nofollow'=>'Do not index or follow'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= ($entry['robots']??'index,follow')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Social title<input name="social_title" value="<?= e($entry['social_title']??'') ?>" maxlength="255" placeholder="Defaults to SEO title"></label><label>Social description<textarea name="social_description" rows="3" maxlength="500" placeholder="Defaults to meta description"><?= e($entry['social_description']??'') ?></textarea></label><div class="structured-field"><label for="social-media">Social image</label><?php if (!$canBrowseMedia): ?><?php if ($socialMediaId>0): ?><input type="hidden" name="social_media_id" value="<?= $socialMediaId ?>"><?php endif; ?><div id="social-media" class="notice neutral compact"><?= $socialMediaId>0?'The existing social image is preserved. ':'' ?>Media Library access is required to change it.</div><?php else: ?><select id="social-media" name="social_media_id"><option value="0">Use featured image or none</option><?php foreach ($mediaAssets as $asset): ?><option value="<?= (int)$asset['id'] ?>" <?= $socialMediaId===(int)$asset['id']?'selected':'' ?>><?= e($asset['label']) ?></option><?php endforeach; ?></select><?php endif; ?></div></div></details></section><?php endif; ?>
</aside>
</div>
</form>
<?php if ($isEdit && $canDelete && (int)$model['enable_trash']===1): ?><section class="danger-zone"><div><strong>Move to Trash</strong><p><?= (int)$model['enable_revisions']===1?'Revision history is retained while the entry remains in Trash.':'The entry can be restored until it is permanently deleted.' ?></p></div><form method="post" action="<?= e(admin_url('/content/'.$model['slug'].'/'.(int)$entry['id'].'/delete')) ?>"><?= Csrf::field() ?><label class="confirm-check"><input type="checkbox" name="confirm_delete" value="1" required> Move this <?= e(mb_strtolower((string)$model['singular_name'])) ?> to Trash.</label><button class="button danger">Move to Trash</button></form></section><?php endif; ?>
<script src="/assets/js/rich-text-editor.js?v=<?= e(app_version()) ?>" defer></script>
<script src="/assets/js/content-safety.js?v=<?= e(app_version()) ?>" defer></script>
<script src="/assets/js/structured-content.js?v=<?= e(app_version()) ?>" defer></script>
