<?php use CMS\Core\Csrf; $trashed=!empty($trashed); ?>
<header class="page-header"><div><p class="eyebrow">Structured content</p><h1><?= e($trashed ? $model['plural_name'].' Trash' : $model['plural_name']) ?></h1><p class="muted"><?= e($model['description'] ?: ('Manage '.mb_strtolower((string)$model['plural_name']).' with the structured fields defined in Content Models.')) ?></p></div><div class="header-actions"><?php if ($trashed): ?><a class="button secondary" href="<?= e(admin_url('/content/'.$model['slug'])) ?>">← Back</a><?php else: ?><?php if ($canDelete && (int)$model['enable_trash']===1 && (int)$trashCount>0): ?><a class="button secondary" href="<?= e(admin_url('/content/'.$model['slug'].'?view=trash')) ?>">Trash · <?= (int)$trashCount ?></a><?php endif; ?><?php if ($canCreate): ?><a class="button" href="<?= e(admin_url('/content/'.$model['slug'].'/new')) ?>">New <?= e($model['singular_name']) ?></a><?php endif; ?><?php endif; ?></div></header>
<?php if (!empty($trashedNow)): ?><div class="notice success">Moved to Trash.</div><?php endif; ?><?php if (!empty($referenceWarningCount)): ?><div class="notice warning"><strong>Relations preserved.</strong> <?= (int)$referenceWarningCount ?> <?= (int)$referenceWarningCount===1?'content entry still references this item':'content entries still reference this item' ?>. Restoring it will restore those relationships; permanent deletion is blocked until the references are removed.</div><?php endif; ?><?php if (!empty($restored)): ?><div class="notice success">Content restored.</div><?php endif; ?><?php if (!empty($purged)): ?><div class="notice success">Content permanently deleted.</div><?php endif; ?>
<section class="card content-card"><form class="filter-bar" method="get" action="<?= e(admin_url('/content/'.$model['slug'])) ?>"><?php if ($trashed): ?><input type="hidden" name="view" value="trash"><?php endif; ?><label class="search-field"><span class="sr-only">Search</span><input type="search" name="q" value="<?= e($search) ?>" placeholder="Search <?= e(mb_strtolower((string)$model['plural_name'])) ?>…"></label><label class="status-filter"><select name="status"><option value="">All statuses</option><option value="draft" <?= $status==='draft'?'selected':'' ?>>Draft</option><option value="scheduled" <?= $status==='scheduled'?'selected':'' ?>>Scheduled</option><option value="published" <?= $status==='published'?'selected':'' ?>>Published</option></select></label><button class="button secondary">Filter</button></form>
<?php if (!$entries): ?><div class="empty-state"><div class="empty-mark"><?= $trashed?'✓':'◇' ?></div><h2><?= $trashed?'Trash is empty.':'No '.e(mb_strtolower((string)$model['plural_name'])).' yet.' ?></h2><p><?= $trashed?'Deleted entries will appear here until restored or permanently removed.':'Create the first '.e(mb_strtolower((string)$model['singular_name'])).' using your structured content model.' ?></p><?php if (!$trashed&&$canCreate): ?><a class="button secondary" href="<?= e(admin_url('/content/'.$model['slug'].'/new')) ?>">Create <?= e($model['singular_name']) ?></a><?php endif; ?></div><?php else: ?><div class="posts-table"><?php foreach ($entries as $entry): ?><article class="post-row<?= $trashed ? ' trash-row' : '' ?>"><div class="post-row-main"><div class="post-title-line"><?php if ($trashed || !$canEdit): ?><strong><?= e($entry['title']) ?></strong><?php else: ?><a href="<?= e(admin_url('/content/'.$model['slug'].'/'.(int)$entry['id'].'/edit')) ?>"><?= e($entry['title']) ?></a><?php endif; ?><span class="status-badge <?= e($entry['status']) ?>"><?= e(ucfirst($entry['status'])) ?></span></div><div class="post-meta"><span><?= (int)$model['has_urls']===1?'/'.e($model['slug']).'/'.e($entry['slug']):'No public URL' ?></span><span>·</span><span><?= e($entry['author_name']) ?></span></div></div><?php if ($trashed): ?><div class="trash-actions"><form method="post" action="<?= e(admin_url('/content/'.$model['slug'].'/'.(int)$entry['id'].'/restore')) ?>"><?= Csrf::field() ?><button class="button secondary small">Restore</button></form><form method="post" action="<?= e(admin_url('/content/'.$model['slug'].'/'.(int)$entry['id'].'/permanent-delete')) ?>"><?= Csrf::field() ?><input type="hidden" name="confirm_delete" value="1"><button class="text-link danger-link" data-confirm="Permanently delete this entry and revision history?">Delete permanently</button></form></div><?php else: ?><div class="post-row-side"><small>Updated</small><strong><?= e(CMS\Core\Posts::displayDate($entry['updated_at'],'j M Y')) ?></strong></div><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?>
<?php if (!empty($pagination) && (int)$pagination['pages'] > 1): ?>
<nav class="pagination" aria-label="<?= e($model['plural_name']) ?> pages">
<?php $baseParams=['q'=>$search,'status'=>$status]; if ($trashed) $baseParams['view']='trash'; $currentPage=(int)$pagination['page']; $totalPages=(int)$pagination['pages']; ?>
<?php if ($currentPage > 1): ?><a href="<?= e(admin_url('/content/'.$model['slug'].'?'.http_build_query(array_merge($baseParams,['page'=>$currentPage-1])))) ?>">← Previous</a><?php else: ?><span></span><?php endif; ?>
<span>Page <?= $currentPage ?> of <?= $totalPages ?> · <?= (int)$pagination['total'] ?> total</span>
<?php if ($currentPage < $totalPages): ?><a href="<?= e(admin_url('/content/'.$model['slug'].'?'.http_build_query(array_merge($baseParams,['page'=>$currentPage+1])))) ?>">Next →</a><?php else: ?><span></span><?php endif; ?>
</nav>
<?php endif; ?>
</section>
