<?php
declare(strict_types=1);

namespace CMS\Core;

final class Env
{
    private static array $values = [];

    public static function load(string $file): void
    {
        if (!is_file($file)) return;
        $lines = file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [];
        foreach ($lines as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#') || !str_contains($line, '=')) continue;
            [$key, $value] = explode('=', $line, 2);
            $key = trim($key);
            $value = trim($value);
            if ($key === '' || !preg_match('/^[A-Z0-9_]+$/', $key)) continue;
            if (($value[0] ?? '') === '"' && str_ends_with($value, '"')) $value = substr($value, 1, -1);
            if (!array_key_exists($key, self::$values)) self::$values[$key] = $value;
        }
    }

    public static function loadConfig(string $file, bool $override = true): void
    {
        if (!is_file($file)) return;
        $values = require $file;
        if (!is_array($values)) return;
        foreach ($values as $key => $value) {
            if (!is_string($key) || !preg_match('/^[A-Z0-9_]+$/', $key)) continue;
            if ($override || !array_key_exists($key, self::$values)) self::$values[$key] = (string)$value;
        }
    }

    public static function get(string $key, ?string $default = null): ?string
    {
        $runtime = getenv($key);
        // Non-empty process environment values remain the highest priority. An
        // empty Docker placeholder must not mask a value securely generated by
        // the browser installer in storage/config.php.
        if ($runtime !== false && $runtime !== '') return $runtime;
        if (array_key_exists($key, self::$values)) return self::$values[$key];
        if ($runtime !== false) return $runtime;
        return $default;
    }

    public static function bool(string $key, bool $default = false): bool
    {
        $value = self::get($key);
        if ($value === null) return $default;
        return filter_var($value, FILTER_VALIDATE_BOOL);
    }

    private function __construct() {}
}
